### ISSUE TITLE
error when you run $npm run start or $npm run dev-start 

### ISSUE THREAD

**Issue by jhuang60** [WSI-Haiyaaaa/project-two#14]
for now, you can run $npm run server to start server until the error is fixed

Error message:
<img width="963" alt="Screen Shot 2021-04-03 at 2 05 22 AM" src="https://user-images.githubusercontent.com/25678885/113471539-adc37980-9422-11eb-818c-c7f07ac70360.png">

**Comment by hyang77** [comment]
The error occurs because of variable process.env.MONGO_ATLAS_PW is undefined. Fixed by installing dotenv package which will load environment variables from .env file.
