### ISSUE TITLE
Database password exposed

### ISSUE THREAD

**Issue by jhuang60** [WSI-Haiyaaaa/project-two#15]
the .sh script requires the username and password of the database, and the current commands have them which is not good. The two possible solutions I can think of:

1. implement a post request to add data
2. find a way to replace the password exposed on the .sh script with an environment variable (possibly writing the script using nodejs?)

**Comment by wxie11** [comment]
@hyang77 Is this issue fixed by https://github.com/WSI-Haiyaaaa/project-two/pull/17?

**Comment by hyang77** [comment]
> @hyang77 Is this issue fixed by #17?

Nope.

**Comment by wxie11** [comment]
We can now remove the shell script and related code @jhuang60
